# Credit to darknight1050 https://github.com/darknight1050/CrashReporter/blob/master/.github/workflows/build-ndk.yml

name: NDK build

env:
    module_id: PauseRemapper
    qmodName: Pause Remapper

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'version-v*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      name: Checkout
      with:
        submodules: true
        lfs: true
    
    - uses: seanmiddleditch/gha-setup-ninja@v3

    - name: Create ndkpath.txt
      run: |
        echo "$ANDROID_NDK_LATEST_HOME" > ${GITHUB_WORKSPACE}/ndkpath.txt
        cat ${GITHUB_WORKSPACE}/ndkpath.txt

    - name: Get QPM
      uses: Fernthedev/qpm-action@v1
      with:
        workflow_token: ${{ secrets.GITHUB_TOKEN }}
        restore: false
        cache: false
        publish: false
        qpm_version: 'version@1.4.1'
        
    - name: QPM Collapse
      run: |
        qpm collapse
    
    - name: QPM Dependencies Cache
      id: cache-qpm-deps
      uses: actions/cache@v4
      env:
        cache-name: cache-qpm-deps
      with:
        path: /home/runner/.local/share/QPM/cache
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('qpm.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: QPM Restore
      run: |
        qpm restore
    - name: List Post Restore
      run: |
        echo includes:
        ls -la ${GITHUB_WORKSPACE}/extern/includes
        echo libs:
        ls -la ${GITHUB_WORKSPACE}/extern/libs
        echo cache:
        ls -la $HOME/.local/share/QPM-RS/cache
        
    - name: Build
      run: |
        cd ${GITHUB_WORKSPACE}
        qpm qmod build
        pwsh -Command ./build.ps1
    - name: Create Qmod
      run: |
        pwsh -Command ./createqmod.ps1
    - name: Get Library Name
      id: libname
      run: |
        cd ./build/
        pattern="lib${module_id}*.so"
        files=( $pattern )
        echo ::set-output name=NAME::"${files[0]}"
    
    - name: Upload so artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.libname.outputs.NAME }}
        path: ./build/${{ steps.libname.outputs.NAME }}
        if-no-files-found: error

    - name: Upload qmod artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{env.qmodName}}.qmod
        path: ./${{ env.qmodName }}.qmod
        if-no-files-found: error